user:
  age: 30
  hobby: 打游戏
  username: 张三

#netty:
#  host: 127.0.0.1
#  port: 7778


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/company
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

#配置静态资源路径
#spring:
#  mvc:
#    static-path-pattern: